apiVersion: v1
kind: Service
metadata:
  name: {{ include "booth-catalog.fullname" . }}
  labels:
    {{- include "booth-catalog.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "booth-catalog.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
